name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release branch version"
        required: true
      microservice-one:
        description: 'microservice-one'
        required: true
        default: true
      microservice-two:
        description: 'Microservice-two'
        required: true
        default: false
      lib:
        description: 'lib'
        required: true
        default: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge changes from develop
        run: |
          SELECTED_MICROSERVICES=""
          if [ "${{ github.event.inputs.microservice-one }}" == "true" ]; then
            SELECTED_MICROSERVICES+="microservice-one,"
          fi
          if [ "${{ github.event.inputs.microservice-two }}" == "true" ]; then
            SELECTED_MICROSERVICES+="microservice-two,"
          fi
          if [ "${{ github.event.inputs.lib }}" == "true" ]; then
            SELECTED_MICROSERVICES+="lib,"
          fi
          SELECTED_MICROSERVICES="${SELECTED_MICROSERVICES%,}" # Remove trailing comma
          IFS=',' read -ra SERVICES <<< "$SELECTED_MICROSERVICES"
          for SERVICE in "${SERVICES[@]}"; do
            git checkout -b release/${{ github.event.inputs.release-version }}
            git merge develop --no-commit --no-ff --strategy-option=ours -- backend-api/$SERVICE
            git add .
            git commit -m "Merge changes from develop for microservice: $SERVICE"
          done        
          git push origin release/${{ github.event.inputs.release-version }}
