name: Create Release/Hotfix Branch

on:
  workflow_dispatch:
    inputs:
      branch_type:
        description: 'Branch type (release/hotfix)'
        required: true
        default: 'release'
      branch_name:
        description: 'Branch name'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set branch type environment variable
        run: echo "BRANCH_TYPE=${{ github.event.inputs.branch_type }}" >> $GITHUB_ENV
          
      - name: Set branch name environment variable
        run: echo "BRANCH_NAME=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV
          
      - name: Create branch
        run: |
          if [[ "${{ env.BRANCH_TYPE }}" == "release" ]]; then
            source_branch="develop"
            target_branch="release/${{ env.BRANCH_NAME }}"
          elif [[ "${{ env.BRANCH_TYPE }}" == "hotfix" ]]; then
            source_branch="main"
            target_branch="hotfix/${{ env.BRANCH_NAME }}"
          else
            echo "Invalid branch type entered."
            exit 1
          fi
          
          git fetch --all
          git checkout $source_branch
          git pull origin $source_branch
          git checkout -b $target_branch
          git push --set-upstream origin $target_branch
          
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
