name: Publish Release and Tag

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Get Current Date
        id: get_current_date
        run: echo "::set-output name=current_date::$(date +'%Y%m%d')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.get_current_date.outputs.current_date }}
          release_name: Release v1${{ steps.get_current_date.outputs.current_date }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Get Commit SHA
        id: get_commit_sha
        run: echo "::set-output name=commit_sha::$(git rev-parse HEAD)"

      - name: Create Tag
        run: |
          git tag v1.0.0 ${{ steps.get_commit_sha.outputs.commit_sha }}
          git push origin --tags
