name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release branch version"
        required: true
      microservices:
        description: "Select microservices"
        required: true
        default: |
          microservice-one
          microservice-two
          lib

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge changes from develop
        run: |
          SELECTED_MICROSERVICES="${{ github.event.inputs.microservices }}"
          IFS=$'\n' read -d '' -ra SERVICES <<< "$SELECTED_MICROSERVICES"
          for SERVICE in "${SERVICES[@]}"; do
            git checkout release/${{ github.event.inputs.release-version }}
            git merge develop --no-commit --no-ff --strategy-option=ours -- backend/$SERVICE
          done
          git commit -m "Merge changes from develop for microservices: $SELECTED_MICROSERVICES"
          git push origin release/${{ github.event.inputs.release-version }}
          
