name: Run Unit Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies and Run Unit Tests
        id: changes
        run: |
          for folder in backend-api/*; do
            if [ -d "$folder" ]; then
              cd "$folder"
              echo "Installing dependencies in  $folder"
              npm ci
              echo "Running tests in $folder..."
              npm test > test-results.txt
              echo "Creating test-results structure for $folder..."
              mkdir -p coverage
              echo "Moving test-results structure for $folder..."              
              mv coverage/lcov-report "$folder"
              cd ..
            fi
            echo "Completed running tests in backend-api folder..."
          done

      - name: Save Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            backend-api/*/test-results.txt
            backend-api/*/coverage
