name: Run Unit Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Determine Modified Folders
        id: changes
        run: |
          for folder in backend-api/*; do
            if [ -d "$folder" ]; then
              cd "$folder"
              echo "Installing dependencies in  $folder"
              npm ci
              echo "Running tests in $folder..."
              npm test
              echo "Creating test-results structure for $folder..."
              mkdir -p ../test-results/$folder
              echo "Copying test-results structure for $folder..."
              cp -r test-results/* ../test-results/$folder
              cd ..
            fi
            echo "Completed running tests in backend-api folder..."
          done

      - name: Save Test Results
        if: ${{ steps.changes.outcome == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results
